name: Deploy Superset to Cloud Run

on:
  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main
    # Only run if files in the superset directory have changed
    paths:
      - 'superset/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push Docker image with Cloud Build
        run: gcloud builds submit . --tag gcr.io/${{ secrets.GGCP_PROJECT_ID }}/superset-insights:latest
  
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy superset-insights \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/superset-insights:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-secrets=SUPERSET_DB_URI=superset-db-uri:latest,SUPERSET_SECRET_KEY=superset-secret-key:latest \
            --add-cloudsql-instances <cubik-analytics-platform:us-central1:superset-insights-db>
